# Include base Makefile
include ../../make/base.mk

# Define and export service specific variables
export VERSION_SUFFIX=-alpine

# Include service template file
include ../../make/service-template.mk
