# Include base Makefile
include ../../make/base.mk

# Define and export service specific variables
export ENTRYPOINT=/home/pipeline-server/run.sh
export DOCKER_ORG ?= intel
export IMAGE_NAME ?= edge_video_analytics_microservice

# Include service template file
include ../../make/service-template.mk
