# Guard to prevent it from being included more than once
ifndef SERVICE_TMPL_MK_DEFINED
SERVICE_TMPL_MK_DEFINED := 1

# The directory this specific makefile resides
make_base_dir := $(dir $(lastword $(MAKEFILE_LIST)))

include $(make_base_dir)/base.mk

# Import variables from hzn.json (file is generated by last target in this file)
-include .hzn.json.tmp.mk

.PHONY: all publish-service deploy-policy

all: publish-service deploy-policy

# Publish a Horizon service (per service.json) and pull image to get its sha256
publish-service:
	hzn exchange service publish -O -f horizon/service.definition.json --pull-image

# Only add a deploy policy if one is specified in "horizon/service.policy.json"
deploy-policy:
ifneq ("$(wildcard horizon/service.policy.json)","")
	hzn exchange deployment addpolicy -f horizon/service.policy.json deploy_$(EDGE_OWNER).$(EDGE_DEPLOY).$(IMAGE_NAME)_$(ARCH)
endif

# This imports the variables from hzn.json
.hzn.json.tmp.mk: horizon/hzn.json
	@hzn util configconv -f $< > $@

endif # SERVICE_TMPL_MK_DEFINED
