# Guard to prevent it from being included more than once
ifndef SERVICE_TMPL_MK_DEFINED
SERVICE_TMPL_MK_DEFINED := 1

# The directory this specific makefile resides
make_base_dir := $(dir $(lastword $(MAKEFILE_LIST)))

SHELL := /bin/bash

# If the users passes TRACE=1, enable shell command tracing
TRACE ?= 0
ifeq ($(TRACE),1)
.SHELLFLAGS = -xc
endif

MAKEFLAGS += --warn-undefined-variables --no-builtin-rules --no-print-directory

# Check all necessary environment variables
include $(make_base_dir)/env.check.mk

export ARCH ?= $(shell hzn architecture)

# Import variables from hzn.json (file is generated by last target in this file)
-include .hzn.json.tmp.mk

.PHONY: all publish-service deploy-policy

all: publish-service deploy-policy

# Publish a Horizon service (per service.json) and pull image to get its sha256
publish-service:
	hzn exchange service publish -O -f horizon/service.definition.json --pull-image

deploy-policy:
	hzn exchange deployment addpolicy -f horizon/deploy_policy_$(IMAGE_NAME).json deploy_$(EDGE_OWNER).$(EDGE_DEPLOY).$(IMAGE_NAME)_$(ARCH)

# This imports the variables from hzn.json
.hzn.json.tmp.mk: horizon/hzn.json
	@hzn util configconv -f $< > $@

endif # SERVICE_TMPL_MK_DEFINED
