# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Include base Makefile
include ../../make/base.mk

# Define and export service specific variables

# Include service template file
include ../../make/service-template.mk
