# Include base Makefile
include ../../make/base.mk

# Define and export service specific variables
export DOCKER_IMAGE_BASE=$(DOCKER_BASE)/app-service-configurable

# Include service template file
include ../../make/service-tmpl.mk
