# Include base Makefile
include ../../make/base.mk

# Define and export service specific variables
export IMAGE_NAME ?= eclipse-mosquitto

# Include service template file
include ../../make/service-template.mk
